package tokens

type TokenType int

const (

	// SINGLE-CHARACTER TOKEN ---
	TOKEN_LEFT_PAREN TokenType = iota
	TOKEN_RIGHT_PAREN
  TOKEN_LEFT_BRACE
	TOKEN_RIGHT_BRACE
  TOKEN_COMMA
	TOKEN_DOT
	TOKEN_MINUS
	TOKEN_PLUS
  TOKEN_SEMICOLON
	TOKEN_SLASH
	TOKEN_STAR
	TOKEN_PERCENT

  // ONE OR TWO CHARATER ---
  TOKEN_BANG
	TOKEN_BANG_EQUAL
  TOKEN_EQUAL
	TOKEN_EQUAL_EQUAL
  TOKEN_GREATER
	TOKEN_GREATER_EQUAL
  TOKEN_LESS
	TOKEN_LESS_EQUAL

  // LITERALS ---
  TOKEN_IDENTIFIER 
	TOKEN_STRING
	TOKEN_NUMBER

  // KEYWORDS ---
  TOKEN_AND
	TOKEN_CLASS
	TOKEN_ELSE
	TOKEN_FALSE
  TOKEN_FOR
	TOKEN_FUNCTION
	TOKEN_IF
	TOKEN_NIL
	TOKEN_OR
  TOKEN_PRINT
	TOKEN_RETURN
	TOKEN_SUPER
	TOKEN_THIS
  TOKEN_TRUE
	TOKEN_VAR
	TOKEN_WHILE

	// SPECIAL TOKENS ---
  TOKEN_ERROR
	TOKEN_EOF
)

var RESERVED_KEYWORDS = map[string]TokenType{
	"and":      TOKEN_AND,
	"class":    TOKEN_CLASS,
	"else":     TOKEN_ELSE,
	"false":    TOKEN_FALSE,
	"for":      TOKEN_FOR,
	"fn":      TOKEN_FUNCTION,
	"if":       TOKEN_IF,
	"nil":      TOKEN_NIL,
	"or":       TOKEN_OR,
	"print":    TOKEN_PRINT,
	"return":   TOKEN_RETURN,
	"super":    TOKEN_SUPER,
	"this":     TOKEN_THIS,
	"true":     TOKEN_TRUE,
	"var":      TOKEN_VAR,
	"while":    TOKEN_WHILE,
}
